#!/usr/bin/env python3

# Read existing priority tier summary, then append new rows based on metrics from each run.
# For each run, look for metrics with names matching the metric_map keys, and extract the count values.
# If a metric is missing, fill in a count of 0 for that tier.
# Output a new TSV with the combined data, and an audit TSV indicating which metrics were present vs filled in.
# The audit TSV can be used to verify that the expected metrics are being generated by the pipeline and correctly processed by this script.

# Run this script from VAP repo root.  Make sure that a copy of the existing priority_tier_summary.tsv (docs/case_studies/cross_runs/) is present in the current directory, and that the results/ directory with run subdirectories is also present.

import pandas as pd
from pathlib import Path

existing_path = Path("priority_tier_summary.tsv")
out_path = Path("priority_tier_summary.appended.tsv")
audit_path = Path("priority_tier_append_audit.tsv")

metric_map = {
    "counts_by_priority_tier__tier_1_high_confidence_candidate": "tier_1_high_confidence_candidate",
    "counts_by_priority_tier__tier_2_moderate_candidate": "tier_2_moderate_candidate",
    "counts_by_priority_tier__tier_3_low_support_or_common": "tier_3_low_support_or_common",
    "counts_by_priority_tier__tier_4_uninterpretable_or_qc_limited": "tier_4_uninterpretable_or_qc_limited",
}

tier_order = list(metric_map.values())

existing = pd.read_csv(existing_path, sep="\t", dtype=str)
rows = []
audit_rows = []

for metrics_path in sorted(Path("results").glob("run_2026_*/metrics/stage_metrics_long.tsv")):
    run_id = metrics_path.parts[1]
    df = pd.read_csv(metrics_path, sep="\t", dtype=str)

    required = {"sample_id", "metric_name", "metric_value"}
    missing_cols = required - set(df.columns)
    if missing_cols:
        raise SystemExit(f"{run_id} missing required columns: {sorted(missing_cols)}")

    sample_ids = df["sample_id"].dropna().unique()
    if len(sample_ids) != 1:
        raise SystemExit(f"{run_id} has unexpected sample_ids: {sample_ids}")

    sample_id = sample_ids[0]

    subset = df[df["metric_name"].isin(metric_map)].copy()
    subset["priority_tier"] = subset["metric_name"].map(metric_map)

    tier_to_values = {}
    for tier, g in subset.groupby("priority_tier"):
        vals = sorted(set(g["metric_value"].dropna().astype(str)))
        if len(vals) > 1:
            raise SystemExit(f"{run_id} has conflicting values for {tier}: {vals}")
        if len(vals) == 1:
            tier_to_values[tier] = vals[0]

    for tier in tier_order:
        if tier in tier_to_values:
            count = tier_to_values[tier]
            status = "source_metric_present"
        else:
            count = "0"
            status = "source_metric_absent_filled_zero"

        rows.append({
            "sample_id": sample_id,
            "run_id": run_id,
            "priority_tier": tier,
            "count": count,
        })

        audit_rows.append({
            "sample_id": sample_id,
            "run_id": run_id,
            "priority_tier": tier,
            "count": count,
            "status": status,
        })

new = pd.DataFrame(rows)
combined = pd.concat([existing, new], ignore_index=True)

combined.to_csv(out_path, sep="\t", index=False)
pd.DataFrame(audit_rows).to_csv(audit_path, sep="\t", index=False)

print(f"Existing rows : {len(existing)}")
print(f"Appended rows : {len(new)}")
print(f"Final rows    : {len(combined)}")
print(f"Wrote: {out_path}")
print(f"Wrote: {audit_path}")
