#!/usr/bin/env python3

# Run from VAP repo root.
# Make sure that a copy of the existing interpretation_label_summary.tsv (docs/case_studies/cross_runs/) is present in the current directory, and that the results/ directory with run subdirectories is also present.
# Make sure that a copy of the stage_funnel_summary.tsv (docs/case_studies/cross_runs/) is present in the current directory, and that it includes all runs being processed.  This is used to pull assay_type and run_classification for each run.

# Run with no arguments.  This will read the existing interpretation_label_summary.tsv, then append new rows based on metrics from each run.
# For each run, look for metrics with names matching the prefix_map keys, and extract the label and count values.  The label is the part of the metric_name after the prefix.
# For example, a metric_name of "counts_by_source_interpretation_label__coding_common_or_low_support" would have a prefix of "counts_by_source_interpretation_label__" and a label of "coding_common_or_low_support".  The count value would be the metric_value for that metric.
# If a metric is missing, fill in a count of 0 for that label.
# Output a new TSV with the combined data, and an audit TSV indicating which metrics were present vs filled in.  The audit TSV can be used to verify that the expected metrics are being generated by the pipeline and correctly processed by this script.

# Run from VAP repo root:
#  scripts/analysis/append_interpretation_label_summary.py

import pandas as pd
from pathlib import Path

existing_path = Path("interpretation_label_summary.tsv")
out_path = Path("interpretation_label_summary.appended.tsv")
audit_path = Path("interpretation_label_append_audit.tsv")

expected_rows = [
    ("source_interpretation_label", "coding_common_or_low_support"),
    ("source_interpretation_label", "coding_uninterpretable"),
    ("source_interpretation_label", "lof_or_missense_rare"),
    ("source_interpretation_label", "lof_rare_clinically_supported"),
    ("source_interpretation_label", "noncoding_common_or_low_support"),
    ("source_interpretation_label", "noncoding_uninterpretable"),
    ("source_interpretation_label", "regulatory_or_transcript_rare"),
    ("variant_origin", "coding"),
    ("variant_origin", "noncoding"),
]

prefix_map = {
    "counts_by_source_interpretation_label__": "source_interpretation_label",
    "counts_by_variant_origin__": "variant_origin",
}

existing = pd.read_csv(existing_path, sep="\t", dtype=str)
stage_funnel = pd.read_csv("stage_funnel_summary.tsv", sep="\t", dtype=str)
rows = []
audit_rows = []

for metrics_path in sorted(Path("results").glob("run_2026_*/metrics/stage_metrics_long.tsv")):
    run_id = metrics_path.parts[1]
    df = pd.read_csv(metrics_path, sep="\t", dtype=str)

    stage_funnel = pd.read_csv("stage_funnel_summary.tsv", sep="\t", dtype=str)

    meta_map = (
        stage_funnel[
            ["sample_id", "run_id", "assay_type", "run_classification"]
        ]
        .drop_duplicates()
        .set_index("run_id")
        .to_dict(orient="index")
    )

    if run_id not in meta_map:
        raise SystemExit(f"{run_id} not found in stage_funnel_summary.tsv")

    sample_id = meta_map[run_id]["sample_id"]
    assay_type = meta_map[run_id]["assay_type"]
    run_classification = meta_map[run_id]["run_classification"]

    observed = {}

    for prefix, axis in prefix_map.items():
        subset = df[df["metric_name"].str.startswith(prefix, na=False)].copy()
        for _, r in subset.iterrows():
            label = r["metric_name"].replace(prefix, "", 1)
            key = (axis, label)
            value = str(r["metric_value"])
            if key in observed and observed[key] != value:
                raise SystemExit(f"{run_id} conflicting values for {key}: {observed[key]} vs {value}")
            observed[key] = value

    for axis, label in expected_rows:
        key = (axis, label)
        if key in observed:
            count = observed[key]
            status = "source_metric_present"
        else:
            count = "0"
            status = "source_metric_absent_filled_zero"

        rows.append({
            "sample_id": sample_id,
            "run_id": run_id,
            "assay_type": assay_type,
            "run_classification": run_classification,
            "summary_axis": axis,
            "interpretation_label": label,
            "count": count,
        })

        audit_rows.append({
            "sample_id": sample_id,
            "run_id": run_id,
            "summary_axis": axis,
            "interpretation_label": label,
            "count": count,
            "status": status,
        })

new = pd.DataFrame(rows)
combined = pd.concat([existing, new], ignore_index=True)

combined.to_csv(out_path, sep="\t", index=False)
pd.DataFrame(audit_rows).to_csv(audit_path, sep="\t", index=False)

print(f"Existing rows : {len(existing)}")
print(f"Appended rows : {len(new)}")
print(f"Final rows    : {len(combined)}")
print(f"Wrote: {out_path}")
print(f"Wrote: {audit_path}")
